{
 "title": "AI Drug Discovery Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AI Service Execution Time (Max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "langchain4j_aiservices_seconds_max",
     "legendFormat": "{{aiservice}} - {{method}}"
    }
   ]
  },
  {
   "title": "AI Service Execution Summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "group by(aiservice, method) (langchain4j_aiservices_seconds_count)",
     "legendFormat": "__auto"
    },
    {
     "expr": "group by(aiservice, method) (langchain4j_aiservices_seconds_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AI Service Success/Failure Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(langchain4j_aiservices_total) by (result)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}